<a href="https://colab.research.google.com/github/007-007-oss/cinema/blob/main/spy%20compare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "name": ["bond","bourne"],
    "agency": ["mi6","cia"],
    "salary": [60000 , 84000],
    "kill count" : [597,21],
    "mission": [26 , 4]
})
print(df.head())

#for finding average kill count,divide kill count by mission by each
average_kill_count = df["kill count"] / df["mission"]

# for finding average kill count,divide kill count by mission
display(average_kill_count)

# find their average salary per mission
average_salary_per_mission = df["salary"] / df["mission"]
display(average_salary_per_mission)

# find their average salary acc to kill count
average_salary_acc_to_kill_count = df["salary"]/df["kill count"]
display(average_salary_acc_to_kill_count)

     name agency  salary  kill count  mission
0    bond    mi6   60000         597       26
1  bourne    cia   84000          21        4

0    22.961538
1     5.250000
dtype: float64

0     2307.692308
1    21000.000000
dtype: float64

0     100.502513
1    4000.000000
dtype: float64